//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.28 at 12:46:04 PM CEST 
//


package si.isystem.cte.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dontCare" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="true" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="triangle" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="circle" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="square" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="solidsquare" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Marks")
public class Marks {

    @XmlAttribute(name = "dontCare")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> dontCare;
    @XmlAttribute(name = "true")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> _true;
    @XmlAttribute(name = "triangle")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> triangle;
    @XmlAttribute(name = "circle")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> circle;
    @XmlAttribute(name = "square")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> square;
    @XmlAttribute(name = "solidsquare")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> solidsquare;

    /**
     * Gets the value of the dontCare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dontCare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDontCare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDontCare() {
        if (dontCare == null) {
            dontCare = new ArrayList<Object>();
        }
        return this.dontCare;
    }

    /**
     * Gets the value of the true property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the true property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getTrue() {
        if (_true == null) {
            _true = new ArrayList<Object>();
        }
        return this._true;
    }

    /**
     * Gets the value of the triangle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triangle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriangle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getTriangle() {
        if (triangle == null) {
            triangle = new ArrayList<Object>();
        }
        return this.triangle;
    }

    /**
     * Gets the value of the circle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the circle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCircle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getCircle() {
        if (circle == null) {
            circle = new ArrayList<Object>();
        }
        return this.circle;
    }

    /**
     * Gets the value of the square property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the square property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSquare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSquare() {
        if (square == null) {
            square = new ArrayList<Object>();
        }
        return this.square;
    }

    /**
     * Gets the value of the solidsquare property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the solidsquare property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSolidsquare().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getSolidsquare() {
        if (solidsquare == null) {
            solidsquare = new ArrayList<Object>();
        }
        return this.solidsquare;
    }

}
